import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'
import './styles.css'
import './typography-responsive.css'
import './law-viewer.css'
import './exam37-law-viewer-baseline.css'
import './registration-law-highlights.js'
import './registration-law-decree-popup.js'
import './tax-law-nav-tree.js'
import './tax-law-exam37-cutoff-normalizer.js'
import './tax-law-point01-leaf-layer.css'
import './tax-law-point01-leaf-layer.js'
import './tax-law-point02-leaf-layer.js'
import './tax-law-point03-leaf-layer.css'
import './tax-law-point03-leaf-layer.js'
import './tax-law-point04-leaf-layer.css'
import './tax-law-point04-leaf-layer.js'
import './tax-law-point05-leaf-layer.css'
import './tax-law-point05-leaf-layer.js'
import './tax-law-point06-leaf-layer.css'
import './tax-law-point06-leaf-layer.js'
import './tax-law-point07-leaf-layer.css'
import './tax-law-point07-leaf-layer.js'
import './tax-law-point08-leaf-layer.css'
import './tax-law-point08-leaf-layer.js'
import './tax-law-point09-leaf-layer.css'
import './tax-law-point09-leaf-layer.js'
import './tax-law-nav-leaves.js'
import './tax-law-exam-drill.css'
import './table-layout.css'
import './mobile-table-scroll-fix.css'
import './mobile-table-viewport.js'
import './exam-wording-standard.js'
import './exam37-baseline-content-layer.css'
import './exam37-baseline-content-layer.js'
import './civil-law-part1-law-first.css'
import './civil-law-part1-law-first.js'
import './civil-law-part1-source-issue-layer.css'
import './civil-law-part1-source-issue-layer.js'
import './civil-law-part2-law-first.js'
import './civil-law-part3-law-first.js'
import './civil-law-part4-law-first.js'
import './civil-law-precision-layer.js'
import './civil-law-precedent-layer.css'
import './civil-law-precedent-layer.js'
import './civil-law-part2-precedent-extra.js'
import './civil-law-part3-precedent-layer.js'
import './civil-law-part3-precedent-extra.js'
import './civil-law-part4-precedent-layer.js'
import './civil-law-part4-precedent-extra.js'
import './civil-law-exam-priority-layer.css'
import './civil-law-exam-priority-layer.js'
import './civil-law-intensive-drill-layer.css'
import './civil-law-intensive-drill-layer.js'
import './civil-law-deep-study-layer.css'
import './civil-law-deep-study-layer.js'
import './civil-law-book-map-exam.js'
import './civil-law-part1-topic-visual.js'
import './civil-law-part2-topic-visual.js'
import './civil-law-part3-topic-visual.js'
import './civil-law-part4-topic-visual.js'
import './civil-law-part1-leaf-check.js'
import './civil-law-part2-leaf-check.js'
import './civil-law-part3-leaf-check.js'
import './civil-law-part4-leaf-check.js'
import './civil-law-integrated-study-flow.js'
import './subject-nav-auto-scroll.js'
import './subject-sidebar-toggle.css'
import './subject-sidebar-fullwidth-collapse.css'
import './subject-sidebar-toggle.js'
import './subject-ui-unified.css'
import './text-overlap-guard.css'
import './text-label-layout-fix.css'
import './unified-study-ui-v2.css'
import './inline-text-flow-fix.css'
import './civil-law-book-map-exam.css'
import './civil-law-part1-visuals.css'
import './civil-law-part3-visuals.css'
import './civil-law-part4-visuals.css'
import './civil-law-part1-leaf-check.css'
import './civil-law-integrated-study-flow.css'
/* 최종 시각 기준: 카테고리=세법 / 본문=민법 */
import './subject-category-tax-standard.css'
import './subject-body-civil-standard.css'
/* 전과목 목차 구조는 4단계 공통 렌더러로 고정 */
import './subject-four-level-nav.js'
/* 모바일 공백 보정은 최종 CSS guard로 유지 */
import './mobile-subject-hero-gap-fix.css'
import './mobile-study-heading-gap-fix.css'

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
